/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Smokey;

/**
 *
 * @author sr115
 */
public class AppetiteChoices extends javax.swing.JFrame {

    /**
     * Creates new form AppetiteChoices
     */
    public AppetiteChoices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dessertTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        strawberryButton = new javax.swing.JButton();
        hamandcheeseButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        guacamoleButton = new javax.swing.JButton();
        reubenDipButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dessertTitle.setFont(new java.awt.Font("The Next Font", 2, 24)); // NOI18N
        dessertTitle.setText("Appetizer");
        dessertTitle.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Freshman", 2, 24)); // NOI18N
        jLabel1.setText("Choices");

        strawberryButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        strawberryButton.setForeground(new java.awt.Color(255, 51, 51));
        strawberryButton.setText("Strawberry Bruschetta");
        strawberryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryButtonActionPerformed(evt);
            }
        });

        hamandcheeseButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        hamandcheeseButton.setText("Ham and Cheese");
        hamandcheeseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamandcheeseButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("The Next Font", 3, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        guacamoleButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        guacamoleButton.setForeground(new java.awt.Color(0, 204, 51));
        guacamoleButton.setText("Traditional Mexican Guacamole");
        guacamoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guacamoleButtonActionPerformed(evt);
            }
        });

        reubenDipButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reubenDipButton.setText("Reuben Dip");
        reubenDipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reubenDipButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reubenDipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(strawberryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hamandcheeseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(guacamoleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(193, 193, 193))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(dessertTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dessertTitle)
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(strawberryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hamandcheeseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guacamoleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reubenDipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String choice;
    
    private void strawberryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryButtonActionPerformed
       this.setVisible(false);
       choice = "Strawberry Bruschetta";
       FinalAppetite rival = new FinalAppetite();
       rival.GetEverything(choice);
    }//GEN-LAST:event_strawberryButtonActionPerformed

    private void hamandcheeseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamandcheeseButtonActionPerformed
       this.setVisible(false);
       choice = "Ham and Cheese";
       FinalAppetite rival = new FinalAppetite();
       rival.GetEverything(choice);
    }//GEN-LAST:event_hamandcheeseButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        String[] hey = {"hey"};
        MainFrame.main(hey);
    }//GEN-LAST:event_backButtonActionPerformed

    private void guacamoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guacamoleButtonActionPerformed
       this.setVisible(false);
       choice = "Traditional Mexican Guacamole";
       FinalAppetite rival = new FinalAppetite();
       rival.GetEverything(choice);
    }//GEN-LAST:event_guacamoleButtonActionPerformed

    private void reubenDipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reubenDipButtonActionPerformed
        this.setVisible(false);
       choice = "Reuben Dip";
       FinalAppetite rival = new FinalAppetite();
       rival.GetEverything(choice);
    }//GEN-LAST:event_reubenDipButtonActionPerformed

    
    
    
    
    /**
     * 
     */
    public static void mainAppetite() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppetiteChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppetiteChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppetiteChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppetiteChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppetiteChoices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dessertTitle;
    private javax.swing.JButton guacamoleButton;
    private javax.swing.JButton hamandcheeseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton reubenDipButton;
    private javax.swing.JButton strawberryButton;
    // End of variables declaration//GEN-END:variables
}
