package Smokey;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sr115
 */
public class DessertChoices extends javax.swing.JFrame {

    /**
     * Creates new form DessertChoices
     */
    public DessertChoices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dessertTitle = new javax.swing.JLabel();
        choicesBackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chocEclairButton = new javax.swing.JButton();
        coconutCreamButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cookiesButton = new javax.swing.JButton();
        walnutBananaBreadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dessert Choices");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        dessertTitle.setFont(new java.awt.Font("The Next Font", 2, 24)); // NOI18N
        dessertTitle.setText("Dessert");

        choicesBackButton.setFont(new java.awt.Font("The Next Font", 3, 18)); // NOI18N
        choicesBackButton.setText("BACK");
        choicesBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choicesBackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Freshman", 0, 36)); // NOI18N
        jLabel1.setText("Choices");

        chocEclairButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chocEclairButton.setText("Chocolate Eclair");
        chocEclairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocEclairButtonActionPerformed(evt);
            }
        });

        coconutCreamButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        coconutCreamButton.setForeground(new java.awt.Color(255, 255, 255));
        coconutCreamButton.setText("Coconut Cream");
        coconutCreamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coconutCreamButtonActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        cookiesButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cookiesButton.setText("Chocolate Chip Cookies");
        cookiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cookiesButtonActionPerformed(evt);
            }
        });

        walnutBananaBreadButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        walnutBananaBreadButton.setForeground(new java.awt.Color(255, 255, 51));
        walnutBananaBreadButton.setText("Walnut Banana Bread Pudding");
        walnutBananaBreadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walnutBananaBreadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(choicesBackButton)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(dessertTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(walnutBananaBreadButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chocEclairButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cookiesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coconutCreamButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dessertTitle)
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chocEclairButton)
                .addGap(18, 18, 18)
                .addComponent(coconutCreamButton)
                .addGap(18, 18, 18)
                .addComponent(cookiesButton)
                .addGap(18, 18, 18)
                .addComponent(walnutBananaBreadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(choicesBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String choice;
    
    private void choicesBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choicesBackButtonActionPerformed
        String[] hey = {"hey"};
        this.setVisible(false);
        MainFrame.main(hey);
    }//GEN-LAST:event_choicesBackButtonActionPerformed

    private void chocEclairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocEclairButtonActionPerformed
        this.setVisible(false);
        choice = "Chocolate Eclair Dessert";
        FinalDessert peace = new FinalDessert();
        peace.GetEverything(choice);
    }//GEN-LAST:event_chocEclairButtonActionPerformed

    private void coconutCreamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coconutCreamButtonActionPerformed
        this.setVisible(false);
        choice = "Coconut Cream Dessert";
        FinalDessert peace = new FinalDessert();
        peace.GetEverything(choice);
    }//GEN-LAST:event_coconutCreamButtonActionPerformed

    private void cookiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cookiesButtonActionPerformed
       this.setVisible(false);
        choice = "Chocolate Chip Cookies";
        FinalDessert peace = new FinalDessert();
        peace.GetEverything(choice);
    }//GEN-LAST:event_cookiesButtonActionPerformed

    private void walnutBananaBreadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walnutBananaBreadButtonActionPerformed
        this.setVisible(false);
        choice = "Walnut Banana Bread Pudding";
        FinalDessert peace = new FinalDessert();
        peace.GetEverything(choice);
    }//GEN-LAST:event_walnutBananaBreadButtonActionPerformed


    
    /**
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DessertChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DessertChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DessertChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DessertChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DessertChoices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chocEclairButton;
    private javax.swing.JButton choicesBackButton;
    private javax.swing.JButton coconutCreamButton;
    private javax.swing.JButton cookiesButton;
    private javax.swing.JLabel dessertTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton walnutBananaBreadButton;
    // End of variables declaration//GEN-END:variables
}
